# Generated by Django 3.1.1 on 2020-09-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200903_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
