# Generated by Django 3.1.1 on 2020-09-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Available', 'Disponible'), ('Out of stock', 'Fuera de Stock')], max_length=200)),
            ],
        ),
    ]
