# Generated by Django 3.1.1 on 2020-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_products_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='pages.Tag'),
        ),
    ]
