# Generated by Django 3.1.1 on 2020-09-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='api_basic.tag'),
        ),
    ]
