# Generated by Django 3.1.1 on 2020-09-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20200910_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(to='api_basic.User'),
        ),
    ]
