# Generated by Django 3.1.1 on 2020-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20200911_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(to='api_basic.User'),
        ),
    ]
